-- SAR reports generated by Gemini AI for compliance filing
CREATE TABLE sar_reports (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_id     UUID NOT NULL
                     REFERENCES transactions(id) ON DELETE RESTRICT,
  generated_by       UUID NOT NULL
                     REFERENCES users(id) ON DELETE RESTRICT,
  report_text        TEXT NOT NULL,
  model_used         VARCHAR(100) NOT NULL
                     DEFAULT 'gemini-2.0-flash',
  prompt_token_count INT,
  output_token_count INT,
  generation_ms      BIGINT,
  status             VARCHAR(30) NOT NULL DEFAULT 'DRAFT'
                     CHECK (status IN ('DRAFT','FINAL','FILED')),
  filed_at           TIMESTAMPTZ,
  filed_by           UUID REFERENCES users(id) ON DELETE SET NULL,
  notes              TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_sar_transaction  ON sar_reports(transaction_id);
CREATE INDEX idx_sar_generated_by ON sar_reports(generated_by);
CREATE INDEX idx_sar_status       ON sar_reports(status);
CREATE INDEX idx_sar_created      ON sar_reports(created_at DESC);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_sar_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sar_updated_at
  BEFORE UPDATE ON sar_reports
  FOR EACH ROW EXECUTE FUNCTION update_sar_timestamp();
