// com.fraudguard.entity.SarReport
package com.fraudguard.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.annotations.UuidGenerator;

/**
 * Compliance Suspicious Activity Report (SAR) entity generated by Gemini AI for FinCEN reporting.
 */
@Entity
@Table(name = "sar_reports")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Slf4j
public class SarReport {

    @Id
    @GeneratedValue
    @UuidGenerator
    @Column(columnDefinition = "uuid", updatable = false, nullable = false)
    private String id;

    @Column(name = "transaction_id", columnDefinition = "uuid", nullable = false)
    private String transactionId;

    @Column(name = "generated_by", columnDefinition = "uuid", nullable = false)
    private String generatedBy;

    @Column(name = "report_text", columnDefinition = "text", nullable = false)
    private String reportText;

    @Builder.Default
    @Column(name = "model_used", length = 100, nullable = false)
    private String modelUsed = "gemini-2.0-flash";

    @Column(name = "prompt_token_count")
    private Integer promptTokenCount;

    @Column(name = "output_token_count")
    private Integer outputTokenCount;

    @Column(name = "generation_ms")
    private Long generationMs;

    @Builder.Default
    @Column(nullable = false, length = 30)
    private String status = "DRAFT";

    @Column(name = "filed_at")
    private OffsetDateTime filedAt;

    @Column(name = "filed_by", columnDefinition = "uuid")
    private String filedBy;

    @Column(columnDefinition = "text")
    private String notes;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt;
}
